name: ' 🚀 release-please'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

## Do not cancel in-progress jobs. This can break the publish flow.
# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    needs:
      - release-please
    uses: ./.github/workflows/publish.yml
    secrets:
      PUBLISH_NPM: ${{ secrets.PUBLISH_NPM }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ needs.release-please.outputs.release_created }}
# cspell:ignore noreply
